# Form implementation generated from reading ui file 'validation.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyotp


class Ui_Validation(object):
    def setupUi(self, Validation):
        self.current_base32 = pyotp.random_base32()
        Validation.setObjectName("Validation")
        Validation.resize(419, 354)
        Validation.setStyleSheet(
            ".QWidget{background-color: #CBB1A0;border-radius: 10px}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Validation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Validation)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Validation)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                      "      color: rgb(231, 231, 231);\n"
                                      "      font: 12pt \"Verdana\" bold;\n"
                                      "      border: None;\n"
                                      "      border-bottom-color: white;\n"
                                      "      border-radius: 10px;\n"
                                      "      padding: 0 8px;\n"
                                      "      background: #CBB1A0;\n"
                                      "      selection-background-color: darkgray;\n"
                                      "}")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Validation)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(16)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Validation)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "      color: rgb(231, 231, 231);\n"
                                    "      font: 15pt \"Verdana\";\n"
                                    "      border: None;\n"
                                    "      border-bottom-color: white;\n"
                                    "      border-radius: 10px;\n"
                                    "      padding: 0 8px;\n"
                                    "      background: #CBB1A0;\n"
                                    "      selection-background-color: darkgray;\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Validation)
        self.pushButton.setEnabled(True)
        self.pushButton.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("color: #842a2d;\n"
                                      "font: 17pt \"Franklin Gothic Book\";\n"
                                      "border: 2px solid #842a2d;\n"
                                      "padding: 2px;\n"
                                      "border-radius: 10px;\n"
                                      "opacity: 100;\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Validation)
        self.pushButton_2.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.clicked.connect(Validation.close)
        self.pushButton_2.setStyleSheet("color: #842a2d;\n"
                                        "font: 17pt \"Franklin Gothic Book\";\n"
                                        "border: 2px solid #842a2d;\n"
                                        "padding: 2px;\n"
                                        "border-radius: 10px;\n"
                                        "opacity: 100;\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Validation)
        QtCore.QMetaObject.connectSlotsByName(Validation)

    def readable_base32(self, base32):
        str = ""
        counter = 0
        while counter != 32:
            if counter % 4 == 0:
                str += f" {base32[counter]}"
            else:
                str += base32[counter]
            counter += 1
        return " ".join(str.split(" ")[1:])

    def retranslateUi(self, Validation):
        _translate = QtCore.QCoreApplication.translate
        Validation.setWindowTitle(_translate("Validation", "Validation OTP"))
        self.label_2.setText(_translate("Validation", "Generated Base32:"))
        self.lineEdit_2.setText(_translate(
            "Validation", f"{self.readable_base32(self.current_base32)}"))
        self.label.setText(_translate("Validation", "Enter Current OTP:"))
        self.pushButton.setText(_translate("Validation", "Validate"))
        self.pushButton_2.setText(_translate("Validation", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Validation = QtWidgets.QWidget()
    ui = Ui_Validation()
    ui.setupUi(Validation)
    Validation.show()
    sys.exit(app.exec())
