# Form implementation generated from reading ui file 'viewAvailable.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_ViewAvailable(object):
    def setupUi(self, ViewAvailable):
        ViewAvailable.setObjectName("ViewAvailable")
        ViewAvailable.resize(695, 640)
        ViewAvailable.setStyleSheet(
            ".QWidget{background-color: #CBB1A0;border-radius: 10px}")
        ViewAvailable.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)

        self.verticalLayout = QtWidgets.QVBoxLayout(ViewAvailable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.label = QtWidgets.QLabel(ViewAvailable)
        font = QtGui.QFont()
        font.setFamily("Karla")
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(
            ".QWidget{background-color: #CBB1A0;border-radius: 10px}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.tableWidget = QtWidgets.QTableWidget(ViewAvailable)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidget.setHorizontalHeaderLabels(["Title", "Author", "Condition"])
        self.load_data()

        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(ViewAvailable)
        self.pushButton.setStyleSheet("color: #842a2d;\n"
                                      "font: 17pt \"Franklin Gothic Book\";\n"
                                      "border: 2px solid #842a2d;\n"
                                      "padding: 2px;\n"
                                      "border-radius: 10px;\n"
                                      "opacity: 100;\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(sys.exit)
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(ViewAvailable)
        QtCore.QMetaObject.connectSlotsByName(ViewAvailable)

    def load_data(self):
        con = sqlite3.connect('./db/test.db')
        query = "SELECT Book_Title, Book_Author, Book_Condition FROM BOOK WHERE Book_Status = \"Available\";"
        result = con.execute(query)
        self.tableWidget.setRowCount(0)
        for row, form in enumerate(result):
            self.tableWidget.insertRow(row)
            for column, item in enumerate(form):
                print(str(item))
                self.tableWidget.setItem(
                    row, column, QtWidgets.QTableWidgetItem(str(item)))

    def retranslateUi(self, ViewAvailable):
        _translate = QtCore.QCoreApplication.translate
        ViewAvailable.setWindowTitle(_translate(
            "ViewAvailable", "Available Books"))
        self.label.setText(_translate("ViewAvailable", "AVAILABLE BOOKS"))
        self.pushButton.setText(_translate("ViewAvailable", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewAvailable = QtWidgets.QWidget()
    ui = Ui_ViewAvailable()
    ui.setupUi(ViewAvailable)
    ViewAvailable.show()
    sys.exit(app.exec())
