# Form implementation generated from reading ui file 'viewBorrowed.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_viewBorrowed(object):
    def setupUi(self, viewBorrowed):
        viewBorrowed.setObjectName("viewBorrowed")
        viewBorrowed.resize(695, 640)
        viewBorrowed.setStyleSheet(
            ".QWidget{background-color: #CBB1A0;border-radius: 10px}")
        viewBorrowed.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(viewBorrowed)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(viewBorrowed)
        font = QtGui.QFont()
        font.setFamily("Karla")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.tableWidget = QtWidgets.QTableWidget(viewBorrowed)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(224)
        self.tableWidget.setHorizontalHeaderLabels(
            ["Title", "Author", "Condition"])
        self.load_data()
        self.verticalLayout.addWidget(self.tableWidget)

        self.pushButton = QtWidgets.QPushButton(viewBorrowed)
        self.pushButton.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("color: #842a2d;\n"
                                      "font: 17pt \"Franklin Gothic Book\";\n"
                                      "border: 2px solid #842a2d;\n"
                                      "padding: 2px;\n"
                                      "border-radius: 10px;\n"
                                      "opacity: 100;\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(viewBorrowed.close)
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(viewBorrowed)
        QtCore.QMetaObject.connectSlotsByName(viewBorrowed)

    def load_data(self):
        con = sqlite3.connect('./db/test.db')
        query = "SELECT Book_Title, Book_Author, Book_Condition FROM BOOK WHERE Book_Status = 'Borrowed';"
        result = con.execute(query)
        self.tableWidget.setRowCount(0)
        for row, form in enumerate(result):
            self.tableWidget.insertRow(row)
            for column, item in enumerate(form):
                print(str(item))
                self.tableWidget.setItem(
                    row, column, QtWidgets.QTableWidgetItem(str(item)))

    def retranslateUi(self, viewBorrowed):
        _translate = QtCore.QCoreApplication.translate
        viewBorrowed.setWindowTitle(
            _translate("viewBorrowed", "Borrowed Books"))
        self.label.setText(_translate("viewBorrowed", "BORROWED BOOKS"))
        self.pushButton.setText(_translate("viewBorrowed", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewBorrowed = QtWidgets.QWidget()
    ui = Ui_viewBorrowed()
    ui.setupUi(viewBorrowed)
    viewBorrowed.show()
    sys.exit(app.exec())
